### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by dimdimich** [tmhub/catalog-configurable-swatches#1]
Hi, can you do screenshot how it looks like on our Argento theme so i can add it to our blog post?

**Comment by vovayatsyuk** [comment]
M001 - https://github.com/tmhub/templatem001/releases/tag/1.4.0
Highlight - https://github.com/tmhub/highlight/releases/tag/2.4.4
Argento - https://github.com/tmhub/argento/releases/tag/1.5.4
